BiocManager::install("scater", version = "3.8")
BiocManager::install("scran", version = "3.8")
BiocManager::install("edgeR", version = "3.8")
BiocManager::install("ConsensusClusterPlus", version = "3.8")
BiocManager::install("GenomicRanges", version = "3.8")
BiocManager::install("IRanges", version = "3.8")
install.packages("tibble")
install.packages("dplyr")
install.packages("stringr")
install.packages("irlba")
install.packages("reshape2")
install.packages("Rtsne")
install.packages("DT")
install.packages("tidyr")
install.packages("splitstackshape")
install.packages("rlist")
install.packages("shiny")
install.packages("shinydashboard")
install.packages("shinyjs")
install.packages("plotly")
install.packages("RColorBrewer")
install.packages("colorRamps")
install.packages("colourpicker")
install.packages("kableExtra")
install.packages("knitr")
install.packages("viridis")
install.packages("ggplot2")
install.packages("gplots")
install.packages("png")
install.packages("gridExtra")
devtools::install_github('wleepang/shiny-directory-input')

#geco
install.packages("geco.utils.tar.gz")
install.packages("geco.visu.tar.gz")
install.packages("geco.unsupervised.tar.gz")
install.packages("geco.supervised.tar.gz")